#!/usr/bin/env sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)

# if the current branch is main, stop the commit
if [ "$BRANCH" = "main" ]; then
  echo "❌ You can't push directly to \"main\". Create a feature branch and open a pull request."
  exit 1
fi

# run svelte checks
bun run check
